services:
  redis:
    image: "redis:latest"
    ports:
      - '::6380'
      - '::6379'
  writer:
    build:
      context: ./writer
    depends_on:
      - redis
    ports:
      - 8080:8080
  reader1:
    build:
      context: ./reader
    depends_on:
      - redis
  reader2:
    build:
      context: ./reader
    depends_on:
      - redis