services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  receiver:
    build:
      context: ./receiver
    depends_on:
      - nats
    ports:
      - 8081:8081
  publisher:
    build:
      context: ./publisher
    depends_on:
      - nats
    ports:
      - 8080:8080

  